# Generated by Django 3.2.16 on 2024-10-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosettings', '0011_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='games', to='prosettings.Game'),
        ),
    ]
