# Generated by Django 3.2.16 on 2024-11-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosettings', '0013_alter_team_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='prosettings.Game'),
        ),
        migrations.AlterField(
            model_name='team',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='games', to='prosettings.Game'),
        ),
    ]
