# Generated by Django 3.2.16 on 2024-11-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosettings', '0015_remove_organization_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='games',
        ),
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_games', to='prosettings.game'),
        ),
    ]
