# Generated by Django 3.2.16 on 2024-11-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosettings', '0016_auto_20241101_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
    ]
