# Generated by Django 3.2.16 on 2024-11-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosettings', '0018_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
