# Generated by Django 3.2.16 on 2024-11-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosettings', '0019_auto_20241101_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team_count',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
